### ISSUE TITLE
Define a variable for atomicorp repo version

### ISSUE THREAD

**Issue by gmarziou** [dj-wasabi/ansible-ossec-server#20]
Hello,

Today I installed this role from ansible galaxy and it failed because `atomic-release-1.0-19` is no longer available on www.atomicorp.com site. 

~~~yaml
- name: RedHat | Install atomicorp repo
  yum: name=https://www.atomicorp.com/channels/atomic/centos/{{ansible_distribution_major_version}}/x86_64/RPMS/atomic-release-1.0-19.el{{ansible_distribution_major_version}}.art.noarch.rpm state=present
~~~

The master on git repo has been updated to `atomic-release-1.0-21`.

What do you think about addiing a role variable for this version?

**Comment by dj-wasabi** [comment]
Hi. Yes you are right, this should be an default variable.

**Comment by dj-wasabi** [comment]
Its a variable now.

**Comment by gmarziou** [comment]
That was fast! Thanks
