### ISSUE TITLE
The `restart ossec-server` handler fails when using the `rules` tag

### ISSUE THREAD

**Issue by dale-c-anderson** [dj-wasabi/ansible-ossec-server#28]
**Description**
When trying to update my custom rules using a tag (instead of running the whole role), I get the following error:
```
$ ansible-playbook ossec-masters.yml --tags rules

PLAY [ossec-masters] *********************************************************

TASK [dj-wasabi.ossec-server : Installing custom local_rules.xml] ************
changed: [server.example.com]

TASK [dj-wasabi.ossec-server : Installing the local_rules.xml (default local_rules.xml)] 
skipping: [server.example.com]

RUNNING HANDLER [dj-wasabi.ossec-server : restart ossec-server] **************
fatal: [server.example.com]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'ossec_init_name' is undefined\n\nThe error appears to have been in '/path/to/roles/dj-wasabi.ossec-server/handlers/main.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: restart ossec-server\n  ^ here\n"}

PLAY RECAP ******************************************************************
server.example.com         : ok=2    changed=1    unreachable=0    failed=1  
```

**Installation method/version**
* Github / latest

**Ansible Version**
* Ansible: 2.5.0
* Python: 2.7.12

**Targetted hosts**
* RHEL 6

**Expected behavior**
The `rules` tag should be able to be used by itself.

**Additional context**
It looks like the problem is just that the variable name from the error message isn't hit when the `rules` tag is used, since the `set_fact` tasks don't share the same tag.

The ansible-ossec-agent role seems to share the same problem.

In any case, I've fixed this on my local, so I will submit a PR.

**Comment by dale-c-anderson** [comment]
The CI build is failing the linting process, but the failure is from a file I did not modify :( 

https://travis-ci.org/dj-wasabi/ansible-ossec-server/jobs/397958595

**Comment by dj-wasabi** [comment]
Yes, restarted job and PR is merged. Thanks again!
